// @todo: extract to db?
export const DailyTags = [
    [
        'harviday',
        'fatherharvi',
        'harviscience',
        'harviart',
    ],
    [
        'harvihappy',
        'harvimontessori',
        'harviimpressive',
        'harviautonomous',
        'harviindependent',
        'harvigrowthspurt',
        'harvidaddysgirl',
    ],
    [
        'harvitantrum',
        'harviinconsolable',
        'harvitesting',
        'harvirestless',
        'harvionenap',
    ],
    [
        'adaday',
        'fatherada',
        'adascience',
        'adaart',
    ],
    [
        'adahappy',
        'adamontessori',
        'adaimpressive',
        'adaautonomous',
        'adaindependent',
        'adagrowthspurt',
        'adadaddysgirl',
    ],
    [
        'adatantrum',
        'adainconsolable',
        'adatesting',
        'adarestless',
        'adaonenap',
    ],
    [
        'harvipickup',
        'adapickup',
        'harvihomefromschool',
        'adahomefromschool',
    ],
    [
        'aligives',
        'alidrunk',
        'aliworkslate',
        'aliworksevening',
    ],
    [
        'workundertime',
        'headsdown',
        'stressed',
        'productiveday',
    ],
    [
        'sick',
        'cook',
        'eattoomuch',
        'sugarsnack',
        'masturbate',
        'separatetv',
        'flossteeth',
    ],
    [
        'gogogo',
        'temper',
        'vulnerable',
        'needtotalk',
        'greatday',
    ],
];

export const DailyTagsColors = [
    'text-red-500',
    'text-yellow-500',
    'text-green-500',
    'text-blue-500',
    'text-purple-500',
];
